### ISSUE TITLE
During development, produce a nice error message for user if database is not running but it should be

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#1051]
When development database is not running and user runs a Wasp command that requires database (like `wasp start` or `wasp db migrate-dev`), right now they will get a bit different error messages each time, coming from different source -> whoever failed to connected to the db. It might come from Server, from Prisma, ... .

Instead, it would be nice if we had more control over it and if we could print a nice error message that informs them that db is not running and how they can run it ("You can run `wasp start db`!").

Good way to do this could be to run `prisma db execute` with `SELECT 1` query and just check if it returned successfully. We could then run this check at the start of any Wasp command that requires db to be running, and if it fails, print nice error message and abort the rest of the wasp command. It is good to do this via prisma because then we don't care if it is sqlite or postgres or whatever.

**Comment by modotte** [comment]
Hello! I wanna try fixing this, but I encountered a couple issues when using `prisma db execute`:

1. This command currently doesn't support MongoDB - https://www.prisma.io/docs/reference/api-reference/command-reference#db-execute. Is MongoDB a part of Wasp's database target or is it okay to ignore it for now?
2. I think you'd need to pass the query via `--stdin` which may require `|` and `echo` on Linux to pass it back to prisma cli. I believe this is fine because users running `wasp` is expected to run on *nix systems, right?

**Comment by Martinsos** [comment]
Ah sorry for being so late to this PR @modotte !
In the meantime @craigmc08 created a PR for this: #1218 , but feel free to take a look at it and comment possibly. I have to yet review it but will do so soon.

**Comment by modotte** [comment]
@Martinsos That's ok! If someone else could do it, that's totally fine :smiley:
