### ISSUE TITLE
Ensure that Wasp nicely warns if `node` is not installed / usable

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#1134]
We have `runNodeCommandAsJobWithExtraEnv` which is used for running `node` commands and it checks that node version is correct. It should also check that `node` itself exists and return nice message if not. It does try to do that right now:
```hs
      `catchIOError` ( \e ->
                         if isDoesNotExistError e
                           then return (ExitFailure 1, "", "Command 'node' not found.")
                           else ioError e
                     )

```
but, we noticed that in some cases instead we get following behaviour (when `node` is not installed):

```
:bee: --- Starting compilation and setup phase. Hold tight... ------------------------


:bee: --- Compiling wasp project... --------------------------------------------------


:bee: --- Starting npm install... ----------------------------------------------------

wasp-bin: node: readCreateProcessWithExitCode: posix_spawnp: failed (Undefined error: 0)
```

@sodic got that behaviour on macbook (m2) without `node`.

Instead, we want a much nicer error message, something like "It seems that you don't have `node` installed! Wasp requires `node` to be installed and in PATH in order to run.".

**Comment by craigmc08** [comment]
I think the behavior @sodic encountered is related to https://github.com/haskell/process/issues/251 (which has been fixed as of the latest version of `process`, v1.6.17.0). I suggest we increase the minimum version in `waspc` from 1.6.13 to 1.6.17 and see if that issue still happens. I don't have access to any m2 devices so I can't test this myself.

If that doesn't fix the error, when something that is not an IO error happens while running `node --version`, we could display that IO error *and* say that they should make sure node is installed. The output from the example you gave could instead end with something like

```txt
An unknown error occurred while running `node --version`:
    wasp-bin: node: readCreateProcessWithExitCode: posix_spawnp: failed (Undefined error: 0)
Check that `node` is installed and in PATH.
```

---

> So we should look into redefining Wasp's dependency on node, and as this issue says, ensure that we warn user clearly and on time if their node is not installed and provide some instructions.

We already have all places that use node going through `Wasp.Generator.Job.Process.runNodeCommandAsJob[WithExtraEnv]`, which checks node version. There is still potential for someone to go around that and run a node command through some ad-hoc system, but I'm not sure of a way to automatically prevent that.

An idea I have is to introduce a function `getValidNodeExecutable :: IO (Either NodeVersionError NodeExecutable)`, which is the only function that can create a value of type `NodeExecutable`. This type just has a single value: its purpose is to act as a proof that node is installed and is a valid version. Then, the node version checking is removed from `runNodeCommandAsJob` and it is modified to take `NodeExecutable` as a parameter, ensuring that it can only be called when that proof is available.

The main advantage of this approach is that we perform the version check only once at the start of a CLI command, if node is needed. Once we have a valid `NodeExecutable`, we can pass it to any functions that require it. Consequently, we achieve three goals: (1) checking the version only once, (2) being able to determine where node is used in Wasp based on function types, and (3) performing the version check very early on, allowing for a safe and consistent exit if necessary.

The cons to this approach that I see:
- Is it worth it?
- Modifying all the functions along the way from CLI command entry point to where node is needed could be tedious and make function signatures messier
  - Mostly not be a big issue for now: node is needed in `wasp deploy`, `wasp start`, which all have pretty short paths to node usage:
    - `wasp start`: Need to modify type for `Wasp.Generator.Start.start`, `Wasp.Generator.ServerGenerator.Start.start`, and `Wasp.Generator.WebAppGenerator.Start.start`
    - `wasp deploy`: Need to modify type for `Wasp.Project.Deployment.deploy`
   - Node is also needed for db commands to run prisma, which looks like it will touch a bunch more functions and is connected to #1051
- What happens if node changes or disappears from PATH between the version being checked and node being used?

**Comment by craigmc08** [comment]
I experimented with implementing what I talked about, but that 2nd issue (modifying functions all the way from the CLI to where node is used) really is a big problem. It adds a lot of noise to the code and I don't think it's worth it. It's looking better to me to keep things the way they are in this regard: making sure we only run node commands through `runNodeCommandAsJob` and accepting that it will check node's version everytime.

**Comment by sodic** [comment]
I agree that dragging Node information through the type system is too much work for too little benefit.

> It's looking better to me to keep things the way they are in this regard: making sure we only run node commands through runNodeCommandAsJob and accepting that it will check node's version everytime. 

This sounds reasonable.

There's one more issue previous comments forgot the mention. We've been doing live user testing, and many users have trouble understanding this output:

![image](https://github.com/wasp-lang/wasp/assets/22752307/2d0c58fb-a8ea-4051-8633-83d26f1bcde3)

They focus on the red text, completely miss the relevant message, and only manage to realize the issue after 30+ seconds.
We would ideally want something like this (one message, straight to the point):
```
$ wasp start
Error: Your node version does not match Wasp's requirements. You are running node 14.21.1.
Wasp requires node ^18.12.0: https://wasp-lang.dev/docs/quick-start#requirements.
$
```
To get this behavior, we'd need to check the Node version for all Wasp commands (regardless of whether they truly require Node). From a DX experience, this is less confusing and feels more robust.

**Comment by craigmc08** [comment]
> To get this behavior, we'd need to check the Node version before running any Wasp command (regardless of whether it truly requires Node), which seems suboptimal. However, from a DX experience, this is less confusing and feels more robust.

This sounds good to me.

> Wasp hangs when I run wasp start in wasp/waspc/examples/todoApp with Node 14.x.x:

I've created an issue (#1212) to track this separately
