### ISSUE TITLE
Restructure docs

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#1172]

**Comment by Martinsos** [comment]
Improve how docs are organized: right now the whole API is under one big "Features" page, which is under "Language".
This should be broken down feature by feature, taken out of Language section, ... .
We also need to balance this with the Guide part.
We probably want to have nice per-feature docs, possibly some Guides/Recipes, and then possibly a more thorough but technical API reference. Or maybe we can skip API reference if it already covered by per-feature docs, at least for now, so we don't have too much duplication to maintain.

**Comment by craigmc08** [comment]
After reading a bunch of the docs recently, here's my notes and ideas:

I agree with splitting up the Features page and moving it out of the Language section. But now it's not clear what the purpose of the Guides section is: we have Auth UI, Sending Emails, Auth Providers, and more in the Guides section, but those are features too! So I suggest we get rid of guides: we'll have Features and Tutorials. Features are about a specific feature of wasp, whereas Tutorials are about accomplishing something with Wasp, e.g. how to make a to-do app or how to integrate Stripe into a Wasp app.

I think there does need to be an API reference section (replacing the current Language section) in addition to the Features section. To illustrate this, try to answer "what fields are valid for a `query` in Wasp and what are their types?" using the Features page. You can do it, but it takes more effort than it should because you have to skim through the entire section.

The Features section should explain the whys and hows of each feature. The API Reference is for when you already know how to use a feature but can't remember the exact details of how to write it, e.g. "Are an action function's parameters `(args, context)` or `(context, args)`?". So Feature pages would be stories, while API Reference pages would be lists of information.

Maybe we can come up with some ways to automatically generate parts of the API Reference to reduce how much work we have to do to maintain it, like using doc comments in the generator templates or creating documentation from `IsDeclType` instances.

**Comment by Martinsos** [comment]
> After reading a bunch of the docs recently, here's my notes and ideas:
> 
> I agree with splitting up the Features page and moving it out of the Language section. But now it's not clear what the purpose of the Guides section is: we have Auth UI, Sending Emails, Auth Providers, and more in the Guides section, but those are features too! So I suggest we get rid of guides: we'll have Features and Tutorials. Features are about a specific feature of wasp, whereas Tutorials are about accomplishing something with Wasp, e.g. how to make a to-do app or how to integrate Stripe into a Wasp app.
> 
> I think there does need to be an API reference section (replacing the current Language section) in addition to the Features section. To illustrate this, try to answer "what fields are valid for a `query` in Wasp and what are their types?" using the Features page. You can do it, but it takes more effort than it should because you have to skim through the entire section.
> 
> The Features section should explain the whys and hows of each feature. The API Reference is for when you already know how to use a feature but can't remember the exact details of how to write it, e.g. "Are an action function's parameters `(args, context)` or `(context, args)`?". So Feature pages would be stories, while API Reference pages would be lists of information.
> 
> Maybe we can come up with some ways to automatically generate parts of the API Reference to reduce how much work we have to do to maintain it, like using doc comments in the generator templates or creating documentation from `IsDeclType` instances.

@craigmc08 this sounds good, I think this is the right approach!
We could possibly have Tutorials and Guides though, where Tutorials are here to teach you about Wasp in general and there would be only a couple of them, while Guides are here to show how to accomplish something specific with Wasp (e.g. how to integrate something). But we might also make them all one thing, just Tutorials.

As for Feature vs API -> you are right, it is just that maintaining API might be a bit cumbersome, so I am a bit tempted to start with just Features and then later provide proper API when we have a bit more resources for it. But let's see, maybe we can do something right now also, depends on how much work it turns out to be.
