### ISSUE TITLE
Docs colourful blocks not readable in night mode

### ISSUE THREAD

**Issue by Umbrien** [wasp-lang/wasp#1181]
**Describe the bug**
In night mode, [colourful blocks](https://github.com/wasp-lang/wasp/blob/561390dfc4d808d5438aabb3df6c4c5d4cf30db2/web/docs/guides/auth-ui.md?plain=1#LL63C11-L63C11) text becomes irreadable.

**To Reproduce**
1. Go to https://wasp-lang.dev/docs/guides/auth-ui#login-form
2. Turn on night mode in navbar

**Screenshots**
![light mode](https://user-images.githubusercontent.com/25881178/235546172-42425dcc-60b7-41ae-ba0e-406e83aa1b21.png)
![night mode](https://user-images.githubusercontent.com/25881178/235546253-8c4cd0cf-614e-4e11-8cf6-0f6b650c2e4c.png)

**Desktop:**
 - OS: Debian 11
 - Browser Chrome, Firefox, Edge

To fix this, we can add additional styling for _every_ colorful block, but why not use MDX components since [Docusaurus supports it](https://docusaurus.io/docs/markdown-features/react)?

**Comment by matijaSos** [comment]
this is a great catch! @infomiho we should keep in mind that the text color will get automatically changed when the theme is switched. The easiest/quickest fix would prob be to go with just bold text instead of background color, but if you want to keep the badge style then you could create a component as @Umbrien suggested and assign it a class variable that is defined both for dark and light theme, like here: https://github.com/wasp-lang/wasp/blob/main/web/src/css/custom.css#L86

**Comment by craigmc08** [comment]
Fixed by 9b86790

![image](https://github.com/wasp-lang/wasp/assets/22552467/c7968a58-1f13-4bb3-b4de-952dc4f4771b)
