### ISSUE TITLE
User can run `wasp new app-with-dashes-in-name`, but dashes in name are not supported by Wasp parser

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#119]
That mean we actually generate invalid Wasp code. We should either ban dashes from name even during creation of new project or allow dashes in parser. I believe we can allow dashes all together, don't see it as a possible problem?

**Comment by Martinsos** [comment]
Hm having identifier with dashes in it does not sound great. Maybe we just forbid it, in CLI? I don't have a super strong opinion, but I would rather be more restrictive here and ensure camelCase is what people use.

**Comment by matijaSos** [comment]
Ok then we should disable it in CLI. Along with other possible stuff, we should validate the given name.

**Comment by Pistus** [comment]
Ran into this when trying to test my first app - I considered this to be the folder, repo and app identifier where I prefer kebab-case as it is easier to read and did not consider that this would create any code issues. In Imba we allow kebab-case by rewriting it to camelCase on compilation. It has some issues, but kebab-is-nice.. 🥙

**Comment by Martinsos** [comment]
@Pistus that makes sense! We could allow name of the app to be more flexible, e.g. kebab-case as you said, and then we convert it to camelCase in the code. This does complicate things somewhat, because we have to be careful on different places that we use correct version: projectName vs projectNameCamelized.
