### ISSUE TITLE
node 19.9.0 cannot be used

### ISSUE THREAD

**Issue by revione** [wasp-lang/wasp#1194]
**Describe the bug**
cannot use node 19.0.0

**To Reproduce**
1. Go to your folder 
2. check you use node 19.9.0
3. Create a new app with wasp
4. go to the app
5. start the app `wasp start`
8. See error

**Expected behavior**
it should be possible to use stable versions or higher.

**Screenshots**
![Captura de pantalla 2023-05-04 a las 15 47 42](https://user-images.githubusercontent.com/11996529/236225715-a122efa7-b7d1-4b8e-9528-8cce18c502e5.png)

**Desktop (please complete the following information):**
 - OS: iOS

**Additional context**
MyApp 
❯ wasp start

🐝 --- Starting compilation and setup phase. Hold tight... ------------------------

🐝 --- Compiling wasp project... --------------------------------------------------

🐝 --- Starting npm install... ----------------------------------------------------

[Server!] Your node version does not match Wasp's requirements. You are running node 19.9.0. Wasp requires node ^18.12.0. Check Wasp docs for more details: https://wasp-lang.dev/docs#requirements.
[Client!] Your node version does not match Wasp's requirements. You are running node 19.9.0. Wasp requires node ^18.12.0. Check Wasp docs for more details: https://wasp-lang.dev/docs#requirements.

❌ --- [Error] Your wasp project failed to compile: -------------------------------

- npm install failed: Setup failed! Server setup failed with exit code 1. Web app setup failed with exit code 1.

❌ --- [Error] Compilation of wasp project failed: --------------------------------

1 errors found

**Comment by Martinsos** [comment]
Hey @revione thanks for the issue!
Unfortunately we do not support later than the latest LTM version of node. We are not a big enough team yet to be able to catch up with latest releases of node.
Did you have a specific problem using older version of Node, specifically 18, that you needed 19 for?

I will close the issue in the meantime since we won't be addressing it, but I am interested to hear what is your use case!
