### ISSUE TITLE
We get "env var not found: DATABASE_URL" from Prisma while doing `wasp build`

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#1282]
Even though everything seems fine, we get this warning from prisma while doing `wasp build`.

@sodic I wonder if this might be connected with our setup of prisma schemas?

![image](https://github.com/wasp-lang/wasp/assets/1536647/e9b8f32a-76c0-4f26-8810-482b2c9fa96d)

**Comment by sodic** [comment]
> @sodic I wonder if this might be connected with our setup of prisma schemas?

I don't think so. I believe this happens because we generate the client outside of Docker (this is where the message comes from) and only set the `DATABASE_URL` variable inside Docker (for the runtime).

It's a consequence of having the schema and the database connection settings defined in the same file.

**Comment by Martinsos** [comment]
@sodic I don't quite get exactly everything you wrote, I would probably have to dive a bit deeper to understand it, but since you seem to have proper understanding, do you have a suggestion on how to fix it?

**Comment by sodic** [comment]
Not yet unfortunately. We talked about this in person, but commenting for future references.

**Comment by Martinsos** [comment]
I might want to look for `prismaErrorContainsDbNotCreatedError` in the code, as we dealt with suppressing a Prisma error there, and it might be a good inspiration for this fix potentially.
