### ISSUE TITLE
Rename password to hashedPassword in our User entity

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#1330]
I saw this is also how Redwood names it. This would make it clearer to the user/reader that the password is hashed?

**Comment by Martinsos** [comment]
Yup that might be a good idea!

**Comment by shyamtawli** [comment]
Hey can I work on it.

**Comment by Martinsos** [comment]
Hey @ELFrancisco4 ! Sure, feel free to go for it. What have you tried so far?
If you go to Wasp docs and search for "user entity", first entry I get is this one: https://wasp-lang.dev/docs/tutorial/auth#creating-a-user-entity -> and you can see here that Wasp expects user entity to contain `password`. I believe idea of this issue is to instead expect it to have `hashedPassword` field.
This will require changes in the Haskell code of Wasp, since this is one of the core concepts in Wasp, as well as updating docs -> it is a bit "advanced" "good first issue".

**Comment by suyog-patil-21** [comment]
If this issue is not assigned. Can I work on this issue?

**Comment by Martinsos** [comment]
> If this issue is not assigned. Can I work on this issue?

Check my comment just above yours!

p.s. I just removed "good first issue" label from this issue, as it is a bit more involved.

**Comment by Martinsos** [comment]
Obsolete with new Auth
