### ISSUE TITLE
Fun JavaScript version of the wasp compiler.

### ISSUE THREAD

**Issue by barak007** [wasp-lang/wasp#141]
Since wasp syntax is very similar to JavaScript I couldn't resist to create a (not good) hyper simple JavaScript version of the parser. It should have all the info to generate the application code with very similar API.

```js
/* wasp.compiler.js */

const types = ["app", "route", "page", "entity", "auth", "action"];

const valuesTypes = ["use", "psl"];

function typeFactory(type, output) {
  return (...args) => {
    output.push({ type, args });
  };
}

function valueFactory(type) {
  return (...args) => {
    return { type, args };
  };
}

function compile(code) {
  const output = [];
  new Function(...types, ...valuesTypes, code)(
    ...types.map((type) => typeFactory(type, output)),
    ...valuesTypes.map((type) => valueFactory(type))
  );
  return output;
}

const waspJsCode = `
app('Conduit', { title: 'Conduit' });

route('/', 'page', 'Main')

page('Main', { component: use('@ext/MainPage.js') })

entity('User', psl\`
    id          Int     @id @default(autoincrement())
    username    String  @unique
    email       String  @unique
    password    String
\`)

auth({
  userEntity: 'User',
  methods: [ 'EmailAndPassword' ]
})

action('signup', {
    fn: use('@ext/action.js', 'signup'),
    entities: ['User']
})

`;

compile(waspJsCode).map((output) => console.log(JSON.stringify(output)));

```

This is just for fun. you can close the issue after having fun with the code.

**Comment by Martinsos** [comment]
Hi @barak007 , wow, this is some cool code! It took me some time to figure out how this works, but I managed to grasp it :).

We were thinking about something similar I have to admit, specifically if Wasp could be just a JS library that really produces just JSON and then that is supplied to the compiler. So not even a compiler, just something you import, configure, and then generate JSON from it.

It could certainly be an option at some moment that we enable compiler to take JSON as an input, JSON that directly maps to the AST, so that we can have multiple frontends, they just need to generate the JSON correctly.

This fun script that you wrote could be a step in that direction.

Anyway, thanks for this :)!
Did you get an opportunity to try out Wasp, any opinions there? Is there something you are interested in? We could always use some help, so if you are interested let us know, we can discuss possibly interesting stuff in Wasp for you.

**Comment by barak007** [comment]
I didn't tried wasp yet. I just saw the syntax and wanted to have fun with it. I think that `data-driven` design is good, 
So the idea of representing the input for the generator as data (JSON) will enable other "languages" to create wasp apps.

Anyhow I liked the idea of DSL for web apps keep on the innovative work.

**Comment by matijaSos** [comment]
This is really col @barak007, love your conc se and elegant implementation! Thanks for sharing :) That is definitely a cool idea, to have an "interface" for anyone/thing to be able to create Wasp app.
