### ISSUE TITLE
Relax node version requirements of Wasp?

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#1433]
Right now, Wasp requires LTS node version, to ensure stability (we had issues where the latest node version would introduce bugs / changes that would cause issues).

However, we had a couple of people already be surprised and even disturbed by this requirement, expecting it to be more relaxed.

So, we might want to relax it indeed! We do then risk npm/node potentially introducing some issues, but maybe it is a good tradeoff if that means adoption will be easier for people.

In that case, we could relax it so that all node versions >= LTS are ok.
We might take this step further and say that odd versions are not ok with Wasp, since `node` maintainers use those as unstable versions, but we also might just let people care about that themselves.

**Comment by Martinsos** [comment]
Related to #1407

**Comment by martinovicdev** [comment]
I think it would be good option to have Node versions above LTS as compatible, especially as we're at even non-LTS version (20.5.1). I would personally just let users know in CLI warning that they're using non-LTS version and it can potentially have issues. 

That way people who are trying out Wasp don't have to care too much about versions and switching just yet and it makes the initial process more streamlined.

**Comment by Zeko369** [comment]
I'd just make this a warning if we really want to (i.e. this is an odd version > LTS it might not work or something like that)

Since the problem I think wasp has right now is that 20 will be LTS in a month and none of the projects outside of wasp can test if they work with 20 so I'd def make it so you can run whatever you want to prevent this in the future (might be a depend miss match or something, users upgrade to wasp 0.12 and it breaks since it's gonna use the the new LTS)

Also agree with @martinovicdev that new (>LTS) odd version should produce warnings (ideally odd <LTS would produce an error since you shouldn't be using that unless you really know why), but testing next gen node should be an option

PS: node odd versions are feature versions that are not supposed to be used in prod (unless you know what you're doing) and won't get an LTS
