### ISSUE TITLE
Fix database initialization

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#1435]
Wasp no longer knows how to initialize (create) the database for a project.

Before:
1. Set the database URL
2. Run `wasp db migrate-dev` or `wasp start`
3. Wasp create the database and start successfully.

Now:
1. Set the database URL
2. Run `wasp db migrate-dev` or `wasp start`
3. Wasp tells you that the database doesn't exist and does not create it.

![image](https://github.com/wasp-lang/wasp/assets/22752307/1b166216-fc28-4209-8eab-833171e271b3)

This is a recent regression. @Martinsos  knows (or he had a feeling) which feature caused it (something Craig implemented IIRC).

**Comment by Martinsos** [comment]
Oh wow, didn't know about this @sodic ! Yeah might likely be caused by that. @craigmc08 added checks, at the start of database commands, that check if database is running -> if it is not, they inform us with an informative error (before we would end up getting some quite confusing errors). I believe in the background we use `prisma db execute` command to test the connection -> but this command should work even if no prisma migrations are in the database, so I am a bit surprised that this would be an issue. Still, it is probably reason to start looking at these changes as the initial starting point.

Here is the commit: https://github.com/wasp-lang/wasp/commit/802e0c5e5d64d81f9775cd919650046e1e165be4 .

**Comment by infomiho** [comment]
This happens because of an internal Prisma behaviour we relied on before.

If you take a look at this piece of their code: https://github.com/prisma/prisma/blob/main/packages/migrate/src/utils/ensureDatabaseExists.ts#L126

It does the check if DB is running in a different way:
1. If there is an error connecting to the **DB server**
  - maybe the DB doesn't exist in **DB server**
  - or the connection really failed
2. If the DB doesn't exist, create it

Our new check for DB connection relies on the DB existing in the **DB server** while our old logic relied on Prisma creating the DB for us and we handled the missing DB case more gracefully.

**Comment by infomiho** [comment]
Now the question remains:

1. Do we adopt the Prisma behaviour in our Haskell based check?
    - This would mean we _somehow_ create the DB if it's missing
3. Can we fall back to using Prisma and their logic yet again?
    - Using a Prisma command to check DB connection that would create the DB as a side-effect?
5. Do now require that the DB existing in **DB server** which mean we accept this regression as the new behaviour

**Comment by sodic** [comment]
@infomiho I vote for option 2. I find it annoying having to connect to the Docker container and manually create a database (Ok, I could be a normal person and use some kind of client, but still).

If we're currently aiming for out-of-the-box eas-of-use, and the second option is trivial to implement, I think it makes sense to go back to that. What do you think?

**Comment by Martinsos** [comment]
Yeah I am also voting for Option 2.
I dont' feel like I have enough info to say more though. I don't understand the regression that was made (what exactly did we use before, and what exactly do we use now?). I also don't understand how Option 1 or Option 2 or Option 3 will be implemented, and what is their impact -> what are the pros/cons?
