### ISSUE TITLE
On signup(), make it clear you are not logged in

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#151]
Right now, if you call signup(), you will not be logged in, you still have to call login(). This has to be made clear in the documentation, or we should make it automatic to be logged in after doing signup().

**Comment by ussgarci** [comment]
Hello, I'd like to work on this issue.

### My Plan
- [ ] understand how `signup` and `login` currently work
- [ ] determine (w/ the help of wasp devs) if we want to update documentation or refactor
- [ ] implement 
- [ ] review/iterate

**Comment by ussgarci** [comment]
Hello @Martinsos, :wave: I wanted to check with you if I should update the documentation for `signup()` to resolve this issue or make it automatic to be logged in after `signup()`.  Thanks!

**Comment by shayneczyzewski** [comment]
Hey @ussgarci! Thanks for making the PR on this one. I think you found the correct spot to add that `login` function call in `signup`. Nice!

However, after thinking about this issue a bit more, I was starting to wonder if perhaps overloading `signup` in this way is perhaps _not_ desirable (or at least, should be configurable). I can imagine in the future a dev may want to add some sort of email confirmation gate to the signup process, etc. and that may make this a non-starter for them. Also, the name `signup` to me does not really imply "and also login". :) So I have a proposal (curious about your thoughts @Martinsos too, since you created this one):
- we either just update the docs to state signup does not also login, or
- we make it configurable

In practice, we already log them in after signup in the form component anyways: https://github.com/wasp-lang/wasp/blob/main/waspc/data/Generator/templates/react-app/src/auth/forms/Signup.js#L19

I surveyed a few other auth APIs and didn't get the idea that doing both automatically was the most common, but could be wrong. Thoughts by all on the above? Thanks!

**Comment by ussgarci** [comment]
You make a good point about this behavior potentially excluding some users who might have particular use cases for `signup` and `login` behavior.  I do like the idea of making it configurable with a default parameter,  something like `signup(userFields, autoLogin=false)` that way the side effect of also logging in the user would have to be explicitly stated.  That said, part of me thinks that the responsibilities of signing up a user and logging in a user should stay separated.  I have no problem with just updating the docs if that is what you guys decide.  Thank you for the feedback!

**Comment by sodic** [comment]
Hi guys, discussing whether this behavior should be configurable is definitely interesting (I also think it should).

But as far as I can tell, we already support login after signup by default, but on the [client](https://github.com/wasp-lang/wasp/blob/4020295740989b3a3b717fac9ebfc807ce07d47a/waspc/data/Generator/templates/react-app/src/auth/forms/Signup.js#L19).

We can discuss whether we should move the support to the endpoint (i.e., have `/signup` log you in, as @ussgarci did in their PR). If yes, we can merge #750, but not without first removing the login API call from the client. Merging the current changes would make us call login twice (once from the signup action, the other time as a separate API call).

**Comment by shayneczyzewski** [comment]
I think at this point I'd probably just vote for a doc update saying `signup` does not `login` and keep them totally separate. I'm not sure that adding a config arg gives us much more help beyond just making the additional separate call if a user needed to. Sounds like @ussgarci is in the same camp. That sound ok to you @sodic and @Martinsos? Thanks all!

**Comment by Martinsos** [comment]
> I think at this point I'd probably just vote for a doc update saying `signup` does not `login` and keep them totally separate. I'm not sure that adding a config arg gives us much more help beyond just making the additional separate call if a user needed to. Sounds like @ussgarci is in the same camp. That sound ok to you @sodic and @Martinsos? Thanks all!

Yup, I think you all together analyzed it really well, and agree with the latest conclusions, which is let's keep them separate then, and just add the docs that clarify the situation!

**Comment by sodic** [comment]
Sure, and just to emphasize one more time: We are already logging users in after they sign up, but this is done [on the client](https://github.com/wasp-lang/wasp/blob/4020295740989b3a3b717fac9ebfc807ce07d47a/waspc/data/Generator/templates/react-app/src/auth/forms/Signup.js#L19).

**Comment by shayneczyzewski** [comment]
> Sure, and just to emphasize one more time: We are already logging users in after they sign up, but this is done [on the client](https://github.com/wasp-lang/wasp/blob/4020295740989b3a3b717fac9ebfc807ce07d47a/waspc/data/Generator/templates/react-app/src/auth/forms/Signup.js#L19).

Yep! 👍🏻

**Comment by ussgarci** [comment]
Hey everyone :wave: as per our discussion I've opened a new PR to update the documentation to clarify the behavior of `signup`.  I also closed my previous PR.  Thanks for all the input!  :+1:
