### ISSUE TITLE
Install Error: Sh: 191: Bad Substitution

### ISSUE THREAD

**Issue by wojcraftinho** [wasp-lang/wasp#156]
When I install WASP on WSL2 (Windows Subsystem For Linux 2) with the Linux install method, it shows an error, but it shows, so the installation is correct. Error Message:
`sh: 191: Bad Substitution`.

I expected the correct installation.

Screenshot:
![image](https://user-images.githubusercontent.com/69644506/101288406-a71b5180-37f6-11eb-8f54-3c993a8567c9.png)

**Comment by Daniellop1** [comment]
Hi there, I believe that uninstalling wasp from its directory and reinstalling it as detailed in https://wasp-lang.dev/docs/tutorials/getting-started would solve the problem.

**Comment by wojcraftinho** [comment]
I forgot to add how to solve it, so:
Search in Google: "add file to path in (your operating system)" or something similiar related to path. Please reply to this issue. If you have similiar problems and you haven't solved it yet.

**Comment by Martinsos** [comment]
Hi @wojcraftinho ! cc @Daniellop1 
This is an actual bug in our install script, but it is different underlying problem then what you described above.

Error message that you pasted, `sh: 191: Bad Substitution`, is the main indicator of a problem.
If you check linke 191 in our [install script](http://get.wasp-lang.dev), you will see that we are doing shell parameter expansion.
This is supported only in bash and is not a part of Posix standard, so it can cause error if being interpreted by a shell that does not support it.

In your case, since you are using WSL2, you probably used relatively new version of Ubuntu on it, and recently Ubuntu changed its default shell from bash to dash. While both bash and dash are Posix compliant, dash does not have all the features that bash has, for example shell parameter expansion that we use in line 191.

Since we want our install script to be portable, I replaced logic in line 191 with Posix compliant logic, so now it will work on any Posix compliant shell, not just bash. For the same reason I replaced `echo -e` with `printf`.
I tested the script with `dash` now and I can confirm it executes successfully.

Your problem with PATH is a problem you would have anyway (and is not something we can solve) -> but if install script was working correctly, it would inform you about it and provide you with instructions on how to solve it. Unfortunately, this error stopped the install script earlier so it didn't get to that point of informing you about this problem.

You can see the fix here: #157  .

**Comment by Daniellop1** [comment]
Today I tried to install it and I also got the same error but now it works. Thanks a lot
