### ISSUE TITLE
Api can't handle FormData

### ISSUE THREAD

**Issue by delruan** [wasp-lang/wasp#1683]
If I want to send FormData to my custom endpoint, but I get an empty body object.

Frontend call:
`const formData = new FormData();
formData.append('file', someFile);
await api.post('/upload', formData);`

Server function:
`
export const upload: Upload = (req, res) => {
console.log(req.body);
res.send();
};
`

console log returns {}

Am I missing something or is this an issue with Wasp?

**Comment by Martinsos** [comment]
@delruan I haven't tried it myself before, but in theory it should work.

`api` is just an `axios` instance with server URL set.
And on the backend, it is node + express with some default middleware.
So nothing super special there!

What if you use the exact same code from above but with `await api.post('/upload', {"foo": "bar"})`? If that works, then we know the `FormData` is a problem, otherwise something else is the issue.

If `FormData` is the issue, then it might be worth looking into configuring Express middleware -> maybe some kind of setting is needed there to ensure correct parsing. I would expect our default middleware to already cover that, since it uses both `json()` and `urlencoded()` middleware as mentioned here https://stackoverflow.com/a/38763341/1509394, but it is worth investigating possibly. Here are our docs no our default middleware https://wasp-lang.dev/docs/advanced/middleware-config and also how you can customize it yourself. But as I said, I think this should actually be ok by default.

What might be a likelier solution to try is actually this post https://stackoverflow.com/a/53126159/1509394, where they mention adding some extra options.
I would try adding
```
headers: {
        'Content-Type': `multipart/form-data;`,
    },
```
first, and if that doesn't help, would also look into adding that `boundary` header, just in case.

Let me know if any of these helps, if not, I can look further into this for you!

**Comment by nosisky** [comment]
I did something like the below to fix it, don't know if there is a better way but this worked for my use case.

```
import { MiddlewareConfigFn } from '@wasp/middleware';
import multer from 'multer';

export const apiMiddleware: MiddlewareConfigFn = (config) => {
  const upload = multer();

  config.set('multer', upload.single('file'));

  return config;
};
```

**Comment by Martinsos** [comment]
@nosisky thanks for sharing, that makes sense! So basically you had to use `multer` to parse the uploaded file and formData from the `req` and put it into `req.file` and `req.body` -> makes sense!
