### ISSUE TITLE
PyCharm / Webstorm IDE support

### ISSUE THREAD

**Issue by simasima121** [wasp-lang/wasp#1801]
Love the tool, but having to use VSCode when most of my daily work uses PyCharm / Webstorm.

Without the IDE plugins it's not really usable, any idea when they're coming out?

**Comment by Martinsos** [comment]
@simasima121 I use emacs, and what I do is open `main.wasp` in vscode and then do the rest in emacs :D. Not the best solution, but most of the time you will not be editing `main.wasp` anyway.

As for IDE plugins for other editors -> what is more likely to happen in the near future is that we will release a TS SDK instead of our custom DSL, so it would be something like `wasp.ts` file in which you define things in very similar way to `main.wasp`, and that means IDE support for all the editors!

**Comment by simasima121** [comment]
@Martinsos lol nice, looks like we've found the same way around it!

That sounds like a good solution - any ideas whens that's coming out, if it's been outlined I'd be happy to help get it out with you

**Comment by Martinsos** [comment]
> @Martinsos lol nice, looks like we've found the same way around it!
> 
> That sounds like a good solution - any ideas whens that's coming out, if it's been scoped I'd be happy to help get it out with you

Thanks a lot for offering help! Probably in the next quarter or two, since it will be a bigger change, which is also why I don't have something simple to share right now -> it will involve some bigger design decisions so we will have first to do a proper RFC and then continue from there.
If you want to track progress, I advise watching this issue https://github.com/wasp-lang/wasp/issues/551 , since it is addressing exactly that! This way you can easily know when it is out + can help us out with some early testing or contributing :).
