### ISSUE TITLE
Rethink server-side Operations API

### ISSUE THREAD

**Issue by infomiho** [wasp-lang/wasp#1909]
### Update by @sodic

When attempting to fix this, I realized our server-side Operations API is virtually unusable:
- Server Operation types are completely unspecified.
- The API isn't properly documented.
- The API expects users to construct Wasp's internal types such as `AuthUser` (which also isn't public or documented). Even if it was documented, it still wouldn't be a great API :)

This happened because we created this API as an afterthought and plugged users into an arbitrary point of our internal RPC architecture. Therefore, the API has never really been user friendly. To make things worse, since it's basically a hook into our internal implementation, it can easily change without us noticing (e.g., it happened with `AuthUser`).

This problem slipped under the radar for so long because calling operations from the server isn't that crucial of a feature, but we should still fix it.

Idea: create a separate wrapper for server side queries that's as clean as possible and does most of the ugly work under the hood.

Fixing this will also fix part of #1958.

### Original issue
Currently we say

> To use a Query, you can import it from `wasp/client/operations` and call it directly. As mentioned, the usage doesn't change depending on whether you're on the server or the client:

and 

> To use an Action, you can import it from `wasp/client/operations` and call it directly. As mentioned, the usage doesn't change depending on whether you're on the server or the client:

which is incorrect. The users shouldn't import the actions and queries on the server from `wasp/client/operation` but rather from `wasp/server/operations`.

Also, we need to explain that they need to provide the `context` as the first argument and then the arguments as the second argument.

Discord thread about this: https://ptb.discord.com/channels/686873244791210014/1218567315185209464/1219591538942804019

**Comment by Martinsos** [comment]
They can also import action directly, from its file. In which case they have to construct the `context` completely on their own, while allegedly, if they import it via `wasp/server/operations`, they don't have to construct it completely on their own, but need to pass just `user` to the context and rest will be added.
We should confirm this and decide if we want to document "raw" import approach also or not.

**Comment by leoschet** [comment]
@Martinsos I'm not sure I follow how to call queries without the `useQuery` hook.

From the docs I had initially understood that wasp would magically add the context, even when calling the function without the hook. Per your last comment, that is not the case, though, and I'm still confused on how to actually do it.

It seems that to directly call the query I must pass the query cache key, plus the user (as context). [The advanced usage section for **actions**](https://wasp-lang.dev/docs/data-model/operations/actions#advanced-usage) says we can get the `queryCacheKey` from the "operation" itself, but that doesn't work:

```typescript
import { getTasks } from 'wasp/client/operations';

// ...

const { data: tasks } = await getTasks(getTasks.queryCacheKey, { user });
```

I would suggest adding to the docs an example of how to call queries with entities without the `useQuery` hook. I would also say the concepts valid for both queries and actions could be in a separate section that appears before queries and actions, perhaps directly in Overview.

**Comment by sodic** [comment]
@leoschet As mentioned on Discord, this issue deals with calling Operations from the server, so it's not really applicable to your situation.

However, the advanced usage docs you linked _do_ talk about calling Operations from client, and you've successfully caught two mistakes. I've created an issue for fixing the docs and improving the API: https://github.com/wasp-lang/wasp/issues/1923

Thanks!

**Comment by sodic** [comment]
Here's a proposal for the API for calling Operations directly on the server.

I'll explore the API on an authenticated Query. Actions are analogous, and unauthenticated operations offer a subset of what's shown here (I'll show it at the end of each example).

## 1 Proposed API
Defining the Operations remains the same, but I'll give a definition to emphasize the relationship between the types.

Assuming an authenticated Query `getFoo` defined as:
```typescript
import { Task, } from 'wasp/entities'
import { type GetFoo } from 'wasp/server/operations'

export const getFoo: GetFoo<Input, Output> = async (args, context) => {
  // ...
}
```
We want to enable the user to do this:
```typescript
import { getFoo } from 'wasp/server/operations'

const payload: Input = { ... }
const user: User = prisma.user.findUnique(...) // This this their 'authEntity'
const result: Output = await getFoo(payload, user)

// If 'getFoo' wasn't authenticated
const result: Output = await getFoo(payload)
```
### 1.1 Alternative APIs
Here's a list of things I considered but gave up on. You can try to change my mind if you disagree :)

#### Users pass in an `AuthUser` object instead of a `User` object:
  - They are better familiar with `User`: it's their entity and is a real entity
  - Passing the `User` object requires no "proprietary" helper functions.
  - Turning a `User` object into an `AuthUser` object is simple
  
#### Users pass in `userId: string` instead of a `User` object:
  - Passing in the ID feels too low-level and raw for my taste.
  - It's easier to make a mistake and specify a non-existent user when you're passing in a `string`. The `User` object forces them to perform a database query.
  
#### Users pass in either a `User` object or a `userId: string`
  - Complicates the signature and is probably unnecessary.
  - Passing in a `string` is error-prone (see above).
  - We can always add this option later if it proves useful, but removing it would constitute a breaking change.

## 2 Implementation of the proposed API
Assuming we go with the proposed API, here's what we have to do.

The true type of `getFoo` (as defined above) is:
```typescript
function getFoo(
  args: Input, 
  context: { 
    entities: Entities,          // All entities the Operation needs, injected by Wasp
    user?: AuthUser | undefined  // AuthUser != User (which they send)
  }
): Promise<Output>
```
Therefore, to make this work, Wasp would have to generate the following wrapper function and make it available through `wasp/server/operations`:
```typescript
// The type 'User' is 'authEntity' defined in the Wasp file.
function getFoo(args: Input, user: User) Promise<Output> { ... }

// If getFoo wasn't authenticated
function getFoo(args: Input) Promise<Output> { ... }
```
The wrapper has to:
 - Construct an `AuthUser` value from a `User` value - simple enough :)
 - Inject the rest of the necessary stuff (i.e., entities) - We already do this in the router and can reuse that logic.

**Comment by infomiho** [comment]
0️⃣  I like the proposed user API, I'm just calling operations with the payload and/or with the `user` 👍 

1️⃣  I'd maybe recommend defining the second param as minimal as possible e.g. `{ id: <type> }`, since we only need the ID to construct the full `AuthUser`. 

2️⃣  Keep in mind that this would be a bit expensive since it would fetch:
- the `User` (if we decide to send the ID)
- the `Auth` object
- all the `AuthIdentity` objects

If they are calling the action in an another action - maybe they already have the constructed `AuthUser` which they can forward to the called action _for free_ in terms of DB queries. I'm not sure if we should be optimizing this - but I wanted to point out the hidden cost which we might avoid. 

Either we accept `{ id: string } | AuthUser` or we have some sort of composable helper method like `getFood(payload, createAuthUser({ id })` 🤷

**Comment by sodic** [comment]
Great points!

I'll address each of them and give my conclusion.

## Answers

>  1️⃣ I'd maybe recommend defining the second param as minimal as possible e.g. { id: <type> }, since we only need the ID to construct the full AuthUser.

Hmm, interesting idea. I was about to accept it, but then realized it suffers from the same problem the raw ID suffers from - it's easy to address a non-existing user.

Also, the type the users see (`{ id: string }`) is not as pedagogical as `User` and I'm afraid it might steer them away from what we want them to do - query the database.

Btw, `{ id: string } | AuthUser` resolves to just `{ id: string }` because one is a supertype of the other (just like `number | 4 == number`). So users would just see `{ id: string }`.

Right after typing that, I figured that we can fix it with overloads ([playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggrsAFgVQM4QE5QLxQN4BQUUAlgCYBcUqwGJAdgOZHWQDGJAhgDbxJqYAysDgAzUVQBENMaMkEAvgQKhIUAGIB7TTiiTR2+QQD0xqABVEJVFE31oiTjcbayUACIANAqLj02wCR2UIwQwFqaAIwAFKiaALZhVkxU9HDxAEaYADRQcOgYVHiklNS0DIxQCgCUVBEA3D5+AUH0IWERkVCxCUkVqelZGLn5mFR8KAW1GtqNvv6BwaHh2jFxiUj9UGmZOXkFReRUNHRMVdMR+CwYYXAYbfqGisqmFlY2dtA8cVCOzq4eTzdMgQVBgEjAL4YRjpCD0YA2G5gG7oeEVKBkEjiTBw4BQTZMVDVJoLVrtFaaABMPQ2yUYA12w32mAAkqUThULrMSS0lh1tNT1n0UttBntRoVYAhJpguZo5s1Fm1lhFBb0CfTRYzcuQAPIYASSjlnAA+Uv4Uzq2iuxBuInuegMmnkShMZks1ls9moskwNlEGAS+PA0FQJHiYG4WJIbE4SqgAFpAVBkZoMtwIPEAHQ8+Mq7QAZhpws1OyGIwO5plWDNxSOZVOlRqNqgdruDydLpe7owICgEE4bEQUHmvLanHobnQ0AA7o48ZwEJo2AlI2FoJpsRgbCBNHAc68WXj4nHIduoHOkphqOq6aQPgA3TDcTScEFuTRYeiaYBAA)). They provide great DX, actually.

> 2️⃣ Keep in mind that this would be a bit expensive since it would fetch...

That is true. There's only a single way it could be made more efficient and it's, as you said, by asking them to always pass an `AuthUser` object.

They'd still have to fetch it themselves, but yes, if they already have it, then it's an improvement.

> getFood(payload, createAuthUser({ id })

As you might have guessed, I'm not a fan of this kind of API. :smile: 
I'd rather sometimes do two an extra database Query then expose our plumbing.

## Conclusion

### For the long term
I like to option of doing `User | AuthUser` (via overloads) and acting differently depending on which one we get.

If you really like the _"pass me only the ID option"_, I'm also OK with `{ id: string } | AuthUser` (via overloads).

The only question is whether we should add a raw `string` to the mix, but I think we can skip that until someone asks for it.

### For the short term

Should we maybe ignore _all_ possible optimizations and just implement the `User` or `{ id: string }` solution?

This API is not super popular, and we might be optimizing prematurely.

**Comment by sodic** [comment]
One more (big) detail I haven't thought about.

Let's put aside the issue of how exactly we pass the user (i.e., `User` vs `AuthUser` vs `{ user: AuthUser }` and others).

We agreed it makes sense to expose an operation like this:
```typescript
const result: Output = await getFoo(payload, user)
```
But what about **operations that don't expect any arguments**, for example:
```typescript
import { type GetBar } from 'wasp/server/operations'

export const getBar: GetBar<void, Output> = async (_args, context) => {
  // ...
}
```
We could make the number of positional arguments depend on whether the operation expects arguments:
```typescript
const foo: Output = await getFoo(payload, user) // Expects an argument
const bar: Output = await getBar(user)          // Doesn't expect an argument
```
But this looks a little janky. Moving the user to the front doesn't solve the problem - the number of arguments now depends on whether the operation is authenticated:
```typescript
const foo: Output = await getFoo(user, payload) // auth: true
const bar: Output = await getBar(payload)       // auth: false
```

Any ideas on what we should do? The only thing I can think of is ditching positional arguments in favor of objects (they do have their benefits anyway, see https://github.com/wasp-lang/wasp/pull/554#discussion_r847449529):
```typescript
// auth: true, takes arguments
const foo: Output = await getFoo({
  payload,
  user,
})

// auth: true, doesn't take arguments
const bar: Output = await getBar({
  user,
})

// auth: false, doesn't take arguments
const baz: Output = await getBaz({}) // kind of dumb
const baz = await getBaz()           // kind of inconsistent
```
@infomiho and @Martinsos please weigh in on those, preferably with something creative that's a gamechanger :)

**Comment by Martinsos** [comment]
@sodic to me it seems pretty clear, but maybe I am missing something: I would stick with how the function is defined.

That means the call would be:
```js
const result = await getFoo(payload, user)
```

And if there are no arguments, then it is just
```js
const result = await getFoo({}, user)
```

which makes sense, because arguments are provided as a single object (payload) where arguments are fields, and in this case there are none so that objects is empty, and all is good.

**Comment by Martinsos** [comment]
That said, I would even go with
```js
const result = await getFoo({}, { user })
```
without feeling bad about it. I don't know if we will want to be putting something more in context in the future or not, and this leaves it flexible while also keeping it consistent with how it is defined.

Look at it this way:
1. Positional arguments are not great when there are optional arguments, so let's say we like non-positional arguments (named arguments). If so, we are going with object.
2. We can't have one single object, because we have args which can be named anything, and we have "options" or we call it "context" which has known fields. So we really have two groups: args, options(context). So it makes sense to have `await getFoo({arg1, arg2, ...}, { user, entities, ... })`

We could in theory go with `await getFoo({args: {arg1, arg2}, context: {user}})`, but we are quite confined that split into args and context is enough, so this is probably too much.

So again, we end up with `getFoo({...}, {...})` as a way to go.

**Comment by sodic** [comment]
> which makes sense, because **arguments are provided as a single object (payload) where arguments are fields**, and in this case there are none so that objects is empty, and all is good.

You'd be 100% percent right if the bold part were true, but unfortunately, it's not :sweat_smile:.
We can (and often do) have:
```typescript
export const getBar: GetBar<number, Output> = async (n, context) => {
  const x = args + 12 // n is just a number
  // ...
}
```
In other words, **`args` can be any JS type**. It's not limited to an object with fields.

**Comment by Martinsos** [comment]
Ah whoops, ok I forgot it can be anything, you are right!

Ok, but in that case, we just stick with whatever they defined, right?

If they don't use the first argument, and define it as `void`, what would you expect them to pass at call site? Since my TS game is not yet 100%, I asked ChatGPT, and it said we should be using `void` for a parameter that is not used (is it making sense?). Suggested instead defining it as `getFoo(_: undefined, ...)`, and then passing `undefined` to it. Which sounds ok to me?

If not, what do you think is the best alternative? Allowing dropping first argument? But then it becomes quite confusing, if tehre is just one argument, which one did you drop, the first one, the second one, ... , right?

**Comment by sodic** [comment]
Had a call with @Martinsos. We are going with:
- **Sending the user inside an object** (`{ user }` instead of `user`) because:
  - It's more consistent with how Operations are defined.
  - it's easily extendable (in the future, users might want to send something else to Wasp's operation machinery and that can't be done with the payload).
  - It's more consistent with other popular APIs (e.g., fetch - first positional argument for the "core functionality", an object for all the extra stuff).
- **Changing the number of positional arguments** (`getFoo(payload, { user })` or `getFoo(payload)`, ` or `getFoo({ user })` depending on `auth` and `void) because:
  - It's most consistent with the client.
  - It's most consistent with the operation's definition.
  - It can express all the edge cases listed in above comments
