### ISSUE TITLE
Introduce a delay (e.g. 1s) for recompilation upon file change

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#191]
Right now it is being triggered a lot, especially by tmp editor files, so this would probably save a lot of unnecessary recompilations.

**Comment by Martinsos** [comment]
More info on the issue: when source file in Wasp is saved (e.g. `main.wasp`, or any file in `ext/` dir), those changes are detected by Wasp CLI and Wasp compiler is run on all of the source files. Wasp compiler then produces output (which is generated Javascript project) and that output is written to the .wasp/out directory. These happens each time a .wasp file or file in ext/ dir gets changed.

The thing is, sometimes there might be rapid changes of files after one another -> for example, if you do some kind of automatic refactoring, multiple files might change in a very short period of time (fraction of second). In that case, since Wasp reacts to any file change, wasp recompilation might be triggered multiple times in a fraction of a second, which is redundant.
Instead, we would rather do recompilation only once in such situation.
Easy way to do this (and how most of the other tools are doing it (e.g. nodemon)) is by introducing a delay between detecting a file change and running the recompilation. So, when file change is detected, we don't do recompilation immediately - instead we start a 1-second timer which will trigger the recompilation after 1 second. If in the meantime more file changes happen, timer is reset.
To put it in other words, when file change happens, we want to wait until 1 second passed without any further file changes -> once that conditioned is satisfied, we run the recompilation.

Main file to look at is `cli/Command/Watch`, I believe most of the changes will be done there.

**Comment by kolharsam** [comment]
ah. okay! Thanks for providing all of the surrounding context @Martinsos. I'll work on this soon!

**Comment by Martinsos** [comment]
@kolharsam I willl be assigning this one to @shayneczyzewski since a lot of time has elapsed since our last chat, but feel free to collaborate with @shayneczyzewski on this moving forward if you wish!
