### ISSUE TITLE
deprecated babel-eslint

### ISSUE THREAD

**Issue by amirHossein-Ebrahimi** [wasp-lang/wasp#205]
**Describe the bug**
```console
Web app (stderr): npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
```
**To Reproduce**
1. follows [Try Wasp in 5 minutes](https://wasp-lang.dev/docs)
2. check with node 12.18.0 and 14.16.0
3. both face an error with `wasp start` command

**Expected behavior**
Update `babel-eslint` to `@babel/eslint-parser` 
or
Change Try wasp in 5 minutes doc to fix it

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version: 18.04.5 LTS
 
**Additional context**
Using nvm with the following versions both faced the same issue
**12.18.0** and **14.16.0**

**Comment by Martinsos** [comment]
@amirHossein-Ebrahimi thanks for reporting!
babel-eslint is not used directly by Wasp -> it is used by react-scripts, which is used by Wasp.
Unfortunately it is also not the only warning reported by react-scripts -> there multiple warnings like this, but we can't really do much about them because some of them are coming from the packages that are used by packages used by react-scripts.
Only thing we can do is update version of react-scripts that Wasp uses as often as we can, which we try to do!
I just bumped version of react-scripts used in Wasp from 4.0.2 to latest 4.0.3, I hope that maybe helps with this one, but as I said, we still have other warnings.
But just to clarify @amirHossein-Ebrahimi , this is not stopping you in any way from using Wasp, right?

**Comment by amirHossein-Ebrahimi** [comment]
Sorry I didn't think it might be `react-scripts` package update warning, cause I used `create-react-app` (with `react-sciprts: 4.0.3`  under the hood) recently and I didn't saw this warning, I had to check the `yarn.lock` file 😅.

For your next question, it somehow blocked the process. It also started with `Web app (stderr):` making it more like an error.

I check out the new version, it didn't kill the `babel-eslint` deprecation warning, but it passes this stage faster.
> It might be a better user experience to use packages like [ora](https://www.npmjs.com/package/ora) showing that the process will continue even when these messages are logged.

**Comment by Martinsos** [comment]
@amirHossein-Ebrahimi don't apologize, it took me some time the first time figure out it is coming from react-scripts! It would be great to somehow get rid of those warnings or offer more context on them, but I haven't yet thought of a smart way to do that.
You can also check stuff like this with `npm list <pkg-name>` (I guess it is similar for yarn), in order to figure out where is the package coming from, instead of looking it up in the yarn.lock.

Hmmm, maybe it didn't block the process, but it instead took long time to install other packages, and it felt like process blocked. And when you ran it again, it was probably faster because portion of packages were already installed.

I like the idea with https://www.npmjs.com/package/ora ! We should use something like that, to provide better feeling for what is happening. I just opened an issue for this: https://github.com/wasp-lang/wasp/issues/207 .
