### ISSUE TITLE
`wasp deploy fly launch my-wasp-app mia` is broken

### ISSUE THREAD

**Issue by trigaten** [wasp-lang/wasp#2318]
`wasp deploy fly launch my-wasp-app mia`  doesn't work because `wasp deploy fly create-db mia` doesnt work because it tries to run a command like:

```
flyctl postgres attach my-wasp-app-red-log-4482-db -a my-wasp-app-red-log-4482-server
```
But it should be running this:
```
flyctl postgres attach my-wasp-app-red-log-4482-db -a my-wasp-app-server-red-log-4482
```
The difference is `my-wasp-app-red-log-4482-server` vs `my-wasp-app-server-red-log-4482`, just the location of the word `server`.

**Comment by trigaten** [comment]
MacOS M2

**Comment by infomiho** [comment]
Thanks for the report! This is a known issue #1588 

The app name you chose `my-wasp-app` was taken and Fly CLI appended some random words at the end of it. Wasp doesn't handle this (yet) - so I'd suggest using a different app name and trying again to deploy :) 

I'll close this issue since we are tracking this in the issue mentioned above.

**Comment by trigaten** [comment]
Thank you, sorry for missing https://github.com/wasp-lang/wasp/issues/1588
