### ISSUE TITLE
Prisma version in `waspc/data/Cli/templates/basic/package.json` should be injected based on `prismaVersion` from `Generator/Common.hs`

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#2329]

**Comment by infomiho** [comment]
Either we inject everything or nothing, that's what we discussed in #2316 😄 

I'd say - if our `package.json` validation rules are good - that should be enough. Why do I say that: because we don't control the injection in other starter templates, so it's better if our system works great without deps version injection - this benefits all the templates, not just the basic one.
