### ISSUE TITLE
We are missing documentation for `app.head`

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#296]
Here is an example of it being used: https://github.com/wasp-lang/wasp/blob/master/waspc/examples/todoApp/todoApp.wasp#L4 .

```
app todoApp {
    title: "ToDo App",
    head: [
        "<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap\" />"
    ]
}
```

We should add short mention of it + description under: https://github.com/wasp-lang/wasp/blob/master/web/docs/language/basic-elements.md#app .

**Comment by lelouchB** [comment]
Hey @Martinsos 
How are you?

I am a JavaScript Developer and Technical Writer and love exploring new technologies, services, platforms, etc. 
Came across Wasp a few days back and I am really enjoying exploring it.

This issue seems like a good place to start. I love documentation.

I wanted to ask if this is still up for grabs?

Thanks :)

**Comment by Martinsos** [comment]
Hey @lelouchB , sure, go for it :)! I will assign you.
