### ISSUE TITLE
Installation instructions are incredibly unsafe

### ISSUE THREAD

**Issue by akkartik** [wasp-lang/wasp#325]
https://wasp-lang.dev currently gives the following command for installing Wasp:

```
curl -sSL http://get.wasp-lang.dev | sh
```

The lack of https makes this incredibly unsafe. You're asking people to run untrusted code that may not even have come from you. Please lead by example about concern for your users' safety. Switch get.wasp-lang.dev to https, and in the meantime point directly to https://raw.githubusercontent.com/wasp-lang/wasp/master/waspc/tools/install.sh on the frontpage. Another alternative is to use a url shortener that supports https.

**Comment by Martinsos** [comment]
Thanks for pointing this out @akkartik !

I just updated how installer script is being downloaded so that it uses https, here are the new instructions (you will see them on updated webpage and docs):
```
curl -sSL https://get.wasp-lang.dev/installer.sh | sh
```

I believe this should be it! I will close the issue but please feel free to comment further if needed.
