### ISSUE TITLE
Use the extensions of `default-extensions` in `.hlint.yaml`

### ISSUE THREAD

**Issue by philderbeast** [wasp-lang/wasp#361]
Please use the extensions of `default-extensions` in `.hlint.yaml`.

https://github.com/wasp-lang/wasp/blob/95e71eb48e9cc8b53848df87f27e06ac89cd02c3/waspc/package.yaml#L12-L16

https://github.com/wasp-lang/wasp/blob/95e71eb48e9cc8b53848df87f27e06ac89cd02c3/waspc/.hlint.yaml#L12

**Comment by Martinsos** [comment]
Thanks for pointing this out, makes sense!

The thing is, hlint by default turns on most of the extensions already, in order to be able to parse as much code as possible, so we ended up adding only those that it didn't have enabled yet, which was QuasiQuotes in our case.

However, I do like the idea of being explicit here instead of relying on hlints default settings, so I think we should add those extensions, it can't hurt for sure.

**Comment by Martinsos** [comment]
Fixed with 2064b9a3e7a0875150fb6688e6ba20ca47cdd4c7
