### ISSUE TITLE
End-to-end blackbox testing of Wasp CLI commands

### ISSUE THREAD

**Issue by shayneczyzewski** [wasp-lang/wasp#434]
It would be nice if we had some testing facility that made it easy/scalable to test the Wasp CLI via end-to-end blackbox style testing. This means we can create a new project and do some validation of the files on disk. We can modify the files in some way, run commands, and observe the outputs (in browser, stdout, and disk). We can test different permutations of commands, etc. All very fuzzy, but this is a research ideation Issue for brainstorming. :D

This would help us with a few things:
1) Ensure we do no introduce any regressions during active dev. For example, some PR may inadvertently change the contents of the `package.json` file, or write some file to the wrong place on disk, or output a new or empty file accidentally, or clean up things incorrectly, etc.
2) Ensure non-breaking changes between releases.
3) Ensure things still work as our underlying dependencies change (e.g. Prisma).

Ideally, this would be integrated into GitHub for CI/CD, but as a first step perhaps it is just something we can run locally. Maybe there are two styles of test to start with:
1) Run a series of commands using two different git commits of the CLI and ensure certain outputs/behavior are identical.
2) Run a series of commands, and specify changes on disk you expect to see at each step.

In an ideal world, it would be nice if this also allowed for some browser based testing as well. But that may be too big for Phase 1.

This would be a great way to rely less heavily on manual testing and shore up the lack of large scale IO testing we have in Haskell atm, as well as ensure we have a good, reliable experience for users.

**Comment by Martinsos** [comment]
This sounds great!

As for comparing two git commits and ensuring certain outputs are identical -> I liked how they do it in Jest (JS test framework), where they have a concept of "snapshots" -> basically they do this diff and inform you which files / data changed, and you have to accept those changes / agree to them. In that context they are usually used for data files, CSS files, generated HTML and similar, since those are harder to unit test.
In our case we could run that on the generated project, and that way if we change certain part of it we will expect changes only in that part and that is great, if only those happens we are happy, if not we fix the error.

I believe more generally such type of test is called "golden test".

**Comment by shayneczyzewski** [comment]
If we use a tool like https://github.com/bats-core/bats-core we can do some pretty interesting things.

If you clone that repo, along with these others, locally:
- https://github.com/bats-core/bats-file
- https://github.com/bats-core/bats-support
- https://github.com/bats-core/bats-assert

You can then run tests like ` ./bats-core/bin/bats test/test.bats` here: https://gist.github.com/shayneczyzewski/2ca926ca37dfcc16147ce426d388f691

The pro here is it is a pretty simple around bash, and you can just use normal commands to do things like modify and read files, as well as use BATS helpers for things like file existence, success/failure, and std output checks.

**Comment by Martinsos** [comment]
Interesting @shayneczyzewski ! I wonder if we could instead use Haskell for defining our tests, so that we get type safety and nicer language than using bash, as I am thinking it might become quite complex to write all the test checks in bash, but that really depends on how complex will this logic turn out at the end I guess. Good to know about this as an option.

**Comment by shayneczyzewski** [comment]
Yep, I agree it depends on what the goal here is and how complex we envision it getting @Martinsos. If we want basic filesystem and stdout checks, something like BATS may be sufficient given how quickly we can get things running. If we need something more complex, it could make sense to invest into a more robust Haskell setup.

**Comment by faassen** [comment]
Another approach I know about is https://www.texttest.org/

This compares log files generated with expected log files, and offer diffs as a failure. I don't know whether it could also use the same technique to compare our build artifacts. The framework has been around for a while and the website present is definitely not the most up to date, but it appears to be a relevant approach.

**Comment by faassen** [comment]
Yeah, I don't know whether filesystem based comparison is a part of TextTest but it may fit the bill as it's not that different from diffing a log file.

I think in general we could get quite far if we could record the output of the logs to the filesystem, and then diff that along with the expected generated output. A visual diff tool like meld will indicate "test failures". :)

**Comment by shayneczyzewski** [comment]
True, that would be nice! I think we may need to beef up our logging in general though if we went a pure log approach, perhaps by adding additional, more verbose, log levels, as well as quieting other things (like node output) that may make it too noisy to compare. Interesting space that will be helpful once we get it rolling. 👍🏻

**Comment by Martinsos** [comment]
> Yeah, I don't know whether filesystem based comparison is a part of TextTest but it may fit the bill as it's not that different from diffing a log file.
> 
> I think in general we could get quite far if we could record the output of the logs to the filesystem, and then diff that along with the expected generated output. A visual diff tool like meld will indicate "test failures". :)

Yeah, just having snapshots (like Jest has snapshots) would probably get us pretty far already!

Haskell -> yeah let's not force it if it doesn't fit the problem, but if it does it might be cool to use it (whenever I start doing something in bash and it grows significantly I tell myself I will not use bash next time :P).
Important: Haskell has this famous library called Turtle: https://hackage.haskell.org/package/turtle , that is specialized for doing shell stuff in Haskell, so that might be a good solution to use Haskell while having a nice experience.

**Comment by Martinsos** [comment]
There is also this: https://hackage.haskell.org/package/tasty-golden -> maybe this way we can utilize our existing testing infrastructure for these tests also? We are using Tasty testing framework at the moment, in Haskell.
