### ISSUE TITLE
Require LTS node version for Wasp

### ISSUE THREAD

**Issue by faassen** [wasp-lang/wasp#442]
Currently Wasp is very flexible in the node version it requires; it can be anything after v12. There's no particular restriction on npm either.

This flexibility doesn't seem to be a major feature - we already recommend in the docs that people install nvm to manage their versions. This flexibility does lead to far more complex testing requirements.

According to this: https://nodejs.org/en/about/releases/

node v12 and v14 currently in maintenance mode. Node v16 is the active LTS version.

In addition, Node ships with particular versions of NPM. While you *can* upgrade your npm under an older version of Node, mixing these is problematic as people generally do not have such mixed combinations. Therefore I recommend we stick to the npm version that comes with Node 16, which is npm 8.

I already noticed some oddness as I did an `start` with Node v14 and then later again with Node v16 -- there was a lot of extra output on updating package-lock versions. (everything did work)

So I think we should switch to require Node v16 (along with npm 8). This requires updating the docs. The github action build pipeline should also be updated to use this node version.

**Comment by Martinsos** [comment]
@faassen I agree! I will be doing new major release of Wasp soon, so I could make this part of that release.

I guess it will come down to updating the docs, updating the CI possibly as you mentioned, and also doing some testing to ensure we didn't break anything. But all together it shouldn't be a problematic change.

We could also modify generated projects so that they demand specific version of npm, by using .nvmrc and `engines` field in package.json, as you did for our web project in https://github.com/wasp-lang/wasp/pull/441/files .

**Comment by Martinsos** [comment]
We are already using .nvmrc and engines field in package.lock json, but we don't have `strict` rule in .nvmrc.
