### ISSUE TITLE
Realworld app returning Network Error

### ISSUE THREAD

**Issue by kalle3e** [wasp-lang/wasp#460]
**Describe the bug**

Downloaded the code, wasp build and wasp start and on registering user it returns "Network Error"

Error: 
From wasp db migrate-dev --- 

Environment variables loaded from .env
Prisma schema loaded from ../db/schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "localhost:5432"

Error: P1001: Can't reach database server at `localhost`:`5432`

Please make sure your database server is running at `localhost`:`5432`.
Error: Migrate dev failed: Migrate (dev) failed with exit code: 1
kitt@x2:~/realworld$ 

**To Reproduce**

Followed the README.md and run docker:
      docker run --rm --publish 5432:5432 -v postgresql-data:/var/lib/postgresql/data --env POSTGRES_PASSWORD=devpass postgres

System message: 2022-02-11 04:21:48.570 UTC [1] LOG:  database system is ready to accept connections

.env in the project root 
/home/kitt/realworld/.env
.env file
![Screenshot from 2022-02-11 16-23-08](https://user-images.githubusercontent.com/64237549/153541675-813b36c8-2f24-499f-95f3-bb0887476afc.png)
 contains
SKIP_PREFLIGHT_CHECK=true;
DATABASE_URL="postgresql://postgres:devpass@localhost:5432/postgres";

**Expected behavior**

Expected the system to create the user

**Screenshots**

**Desktop (please complete the following information):**

Laptop, Ubuntu 20.04, Chrome V 97.0.4692

**Additional context**

Error: migrating database
Error: P1001: Can't reach database server at `localhost`:`5432`

Please make sure your database server is running at `localhost`:`5432`.
Error: Migrate dev failed: Migrate (dev) failed with exit code: 1

**Comment by kalle3e** [comment]
Hi Martin, thanks your your reply. 

I run the realworld app on my laptop that has ubuntu 20.04 

The db is run by docker run --rm --publish 5432:5432 -v postgresql-data:/var/lib/postgresql/data --env POSTGRES_PASSWORD=devpass postgres

Message from this command: 
![Screenshot from 2022-02-11 18-53-33](https://user-images.githubusercontent.com/64237549/153555307-ca6994ff-1d8a-4d3e-ad23-c0cd1b375be5.png)

wasp db migrate-dev

Migration done.
Copying migrations folder from Prisma to Wasp project...
Done copying migrations folder.
All done

![Screenshot from 2022-02-11 18-35-43](https://user-images.githubusercontent.com/64237549/153555588-f3bd7b9f-44d1-4b69-821f-61c10e723117.png)

Now getting error:
![Screenshot from 2022-02-11 18-56-50](https://user-images.githubusercontent.com/64237549/153555703-bd03a442-6d23-469e-8b51-a202f3f15b77.png)

I run realworld app in /home/kitt on ubuntu 20.04, not in a docker container. Also after running postgres container I leave it  on, that's why we can see the error about the "2022-02-11 07:47:35.824 UTC [54] LOG:  invalid length of startup packet" . Not sure when this error actually comes up, probably when I do "wasp start".

**Comment by Martinsos** [comment]
Hmmmm, so it is not an issue related to Wasp, instead it seems to do with the Docker image for Postgresql.

I found some possibly related issues here:
- https://github.com/MIT-LCP/mimic-code/issues/684
- https://github.com/docker-library/postgres/issues/886

I also found others mentioning the issue on different places, but I can't seem to find one clear answer pointing to a well defined problem.

I removed my local postgres docker image, to make sure I pull the latest one, hoping that will replicate the problem you are having, but no luck there - it works fine for me and I don't get any "invalid length of startup packet" messages - not when doing stuff via Wasp.

One way I can get "invalid length of startup packet" messages is if I try opening `localhost:5432` in the browser -> which makes sense, because it sends HTTP packages but postgres server is expecting something else, not HTTP requests.

So my question would be: when do you get that error? If when visiting `localhost:5432` in browser, then that is probably ok, and not a problem at all. What about when using Wasp -> does Wasp work for you now? After you turn on the database, and after you do `wasp db migrate-dev` and then `wasp start`, is everything ok? If you then try to sign in and create new user, does that work?

**Comment by kalle3e** [comment]
Bravo, thanks very much Martin. I've got it working now thanks! I think I ran the db docker command outsite of the project dir and then I tried to fix problems running the localhost:5432 on the browser, but you said we don't do that. All good! Happy to have a look around with the code and wasp. It helps when you're more confident with working with a docker container to start with.

**Comment by Martinsos** [comment]
@kalle3e great, I am glad we figured it out! Good luck with Wasp and feel free to reach out if you have any questions/feedback, either here or on our Discord server!

**Comment by kislaySinha1999** [comment]
can u plz explain how u solved this problem in a lil detail?

**Comment by kalle3e** [comment]
It’s so long ago so it’s diff Otto remember exactly. I think o went back
and follow the step by step instructions again. Also take note of what
Martin says regarding the image, running using localhost. Also take care of
the database migration step. If required, delete the generated files and
start again. Hope it helps.

**Comment by Martinsos** [comment]
> can u plz explain how u solved this problem in a lil detail?

Are you experiencing similar issue? Let me know exactly what you are struggling with and I can try to help!
