### ISSUE TITLE
Consider using `prisma migrate status` or `prisma db pull` to improve DB migration warnings

### ISSUE THREAD

**Issue by shayneczyzewski** [wasp-lang/wasp#461]
Right now, we rely on a migrate checksum to know if the user has migrated locally. Should we use the actual database (via `prisma migrate status`) in some way? Let's think about it.

Some pros are we can determine if users have manipulated the database from under us, and we can also reduce unnecessary warnings on initial checkout/clean.

However, a con is our checksum approach lets us know if they have changed their schema.prisma in a way that needs a migration to take effect, and `prisma migrate status` does not check for this.

**Comment by Martinsos** [comment]
We have:

**schema.prisma <-> migrations <-> db**

and challenge is recognizing when any of these are our of sync, so that we can warn developer, so they may take appropriate actions based on that.

What `prisma migrate dev` does is sync _schema_ with _migrations_ , and then also apply _migrations_ to the _db_. So it takes care of everything.

Right now, we use our manual "checksum" approach to track if _schema_ is out of sync with the _migrations_. That works good -> we might produce false negative sometimes (false warning), but never a false positive, which is great.

However, we don't have a mechanism to track if _migrations_ got out of sync with the _db_.
This could happen if developer manipulates database manually (modifies db schema) or if they provide a different database, that doesn't have correct schema.
We could track this with `migrate status` -> it might be enough in practice to do it only at the beginning of `wasps start`, since it is a relatively expensive operation, and since we can assume developer is not messing up the database manually while running `wasp start`.
So, besides checking the checksum on every compile to ensure that _schema_ is in sync with the _migrations_, we could also run `migrate status` on `wasp start` to ensure _migrations_ are in sync with the _db_.

There is also another interesting option, and that is `prisma db pull`. It creates schema.prisma based on the database schema. So the opposite operation of `migrate` or `db push`! We could in theory use this to check if _schema_ is in sync with the _db_ (skipping the check for migrations). Assuming `prisma db pull` is exact reverse of `migrate`, which might not be the case though.
If `db pull` would be interesting, we would also probably do it only at the start of the `wasp start`.

**Comment by shayneczyzewski** [comment]
Your recap above was super helpful to remind me of what we were trying to do here @Martinsos, so thanks! :D 

Did some initial research today, and it seems `prisma db pull` will overwrite our schema. We could move it somewhere as a backup, then diff and revert, etc. but I think I found an easier way to see if DB matches schema.

If we are in a situation where we do not know the state of the database, we should actually do two checks:
- DB vs migrations: `prisma migrate status --schema ../db/schema.prisma`
  - Look for "Database schema is up to date!" in the output (sadly no exit code check)
- DB vs schema: `prisma migrate diff --from-schema-datamodel ../db/schema.prisma --to-url "$DATABASE_URL" --exit-code`
  - Look for non-zero exit code

NOTE: There is also a `--from-migrations` option for `prisma migrate diff`, but that requires us to supply a `--shadow-database-url` where it will temporarily apply the migrations to diff the databases. If we just generate some random DB, it will error out with `Database 'todoapp-shadow' does not exist on the database server at 'localhost:5432'.` I figure better to not go down this route of creating and removing shadow DBs like `prisma db migrate` does.

Armed with the above two checks, the idea would be to check _both_ of these whenever we do not see our `db/.schema.prisma.wasp-migrate-checksum` file. If they both come back in sync, we could in theory just generate that file. The reason we want to check both and not just `prisma migrate status` for example is they may have done a `wasp clean` after editing their Entity, but they did not create and apply a new migration for it yet (by running `wasp db migrate-dev`). So in essence, if both of those say they are up to date with the DB, we can mark it as ok and then let Wasp just detect schema drift normally thereafter. Sound like a plan?

**Comment by Martinsos** [comment]
Sounds good to me @shayneczyzewski , and I also appreciated my old comment, it got me up to speed quickly :D!

Just to check -> what are our use cases, when do we care about syncing stuff and which stuff? So, let's say they pull some changes into the project -> they now have some migrations in their wasp project, but database might not be reflecting those. Also there might be no migrations in the generated project. Also, their schema might not be reflecting migrations. So we want to detect any of those I think. I guess we don't care about migrations in the generated project though, those will be created when needed?
So what we do is maintain that checksum to compare migrations dir and schema file.
So the only thing we need to check is if db is up to date with migrations, right? That we can do by using any of those two commands you listed, I think, right? As long as we generate needed stuff (migrations, schema). So it sounds to me like one of those should be enough? We could do two, but it sounds a bit redundant? But maybe I am missing something here? Maybe we additionally ensure migrations and schema are in sync although we actually already have a mechanism for that?
