### ISSUE TITLE
Refactor how Wasp generates JavaScript imports

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#574]
Wasp currently generates JavaScript imports in two distinct ways:
- For generating imports from user code ("ext imports"), we generate the entire import statements inside Haskell: https://github.com/wasp-lang/wasp/blob/main/waspc/src/Wasp/Generator/JsImport.hs
- For (I believe) all other use cases, we use templates. Imports inside templates look something like `import {= importWhat =} from {= importPath =}`, while the values come from the generator. Check the router for an exmple: https://github.com/wasp-lang/wasp/blob/main/waspc/data/Generator/templates/react-app/src/router.js

Perhaps it makes sense to centralize/unify the logic for generating imports. If anything, it's less confusing and more easily extendable (for example, if we ever end up generating something other than JavaScript). Then again, it makes sense to wait until we decide what we're going to do about our templates. Are they staying as-is for the time being, or are we planning to do some refactoring (e.g., moving things to the runtime)?

**Comment by Martinsos** [comment]
I think templates are certainly staying for now, in some capacity. We might likely move some stuff to runtime, but it will probably take long time till we completely drop templates, if ever. And even then, we will need ways to generate imports. So I think the idea of having a central logic in Haskell for generating valid JS import statement is a good idea in any case! And as you said, we can use it anywhere then.

To make this issue a bit more straightforward, where would we likely place this function? Maybe in `Generator/JsImport`, smth like that? I guess function would be called smth like `makeJsImportStatement :: String -> Path Posix b f -> String`? Maybe it could accept higher resolution arguments, smth like `(Maybe String, [(String, Maybe String)]` instead of just `String`?

**Comment by sodic** [comment]
Hm, I'm guessing the arguments would represent a list of named imports with optional aliases? Sure, why not (although I think we already have a specific type that captures this information).

I had in mind something along the lines of making the function in https://github.com/wasp-lang/wasp/blob/main/waspc/src/Wasp/Generator/JsImport.hs public (with possible rearrangement/renaming).

**Comment by Martinsos** [comment]
Oh yeah sure we could reuse that! I just sketched something, even better if we can put more structure into it / reuse what we have.
