### ISSUE TITLE
Fix redundant file generation in Wasp

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#594]
Wasp currently doesn't differentiate between `ext/*` files used by the client and `ext/*` files used by the server. Instead, it copies all of them to both generated source directories.

We should find a way to optimize this and avoid generating redundant files - they take up time, space, and interfere with the IDE support (e.g., JetBrains reports duplicate code).

**Comment by Martinsos** [comment]
There are two main approaches I can think of:
1. Wasp figures out which files should go to client/server/both.
2. Dev tells Wasp which files should go to client/server/both.

It could also be some mix of both.

To do (1), we would need to do something smart -> evaluate files to some degree in order to figure out which file goes where, who is importing whom. The problem is, JS has possibility to do dynamic imports during runtime, so I don't think we can really ever properly figure out, with 100% certainty, which file goes where, since it can in theory depend on user input (that would be really weird and likely insecure though).

So in theory, going with (2) is the safest and simplest option and we know it will work.
Here is an existing issue discussing one of the approaches for doing (2): https://github.com/wasp-lang/wasp/issues/522 . There are also other ways to do it probably (file suffixes, declarations, ...).

What could work in practice is approach (1) with an option to be explicit in some very special cases (so (2) as a fallback in special situations).

One big question though is, how obvious should it be to the users which code is client, which is server, ... ? On one hand, it sounds cool that it somewhat all mixes up, especially since some of the code is used on both sides (both web and node). On the other hand, that can also become confusing -> "is this node now?" -> "Oh, I thought I was writing server code but no this is client code." and similar.
So I am not sure what is better for developer experience -> being very explicit (client/ server/ iso/) or mixing it all up, and figuring this out will also guide our efforts in this issue.
