### ISSUE TITLE
Improve access to Entities in Jobs

### ISSUE THREAD

**Issue by shayneczyzewski** [wasp-lang/wasp#607]
Currently, the only way to access Entities in Jobs is to directly import `prisma` and operate on them directly. Here is an example from Waspleau where I made a helper function utilized by a Job, but you can imagine a Job doing this directly:

```javascript
import Prisma from '@prisma/client'

const prisma = new Prisma.PrismaClient()

export function upsertMetric({ name, value } = {}) {
  return prisma.metric.upsert({
    where: { name },
    update: { name, value: String(value) },
    create: { name, value: String(value) }
  })
}
```

The other option would be to import Actions and call them. However, it would be better if we had a nicer way to associate Entities and Jobs.

Taking a step back, for Actions we define referenced Entities in wasp:
```css
action createTask {
  fn: import { createTask } from "@ext/actions.js",
  entities: [Task]
}
```

And in the corresponding JS we can access via args `context.entities.Task`.

One possible gotcha with Jobs could be if we serialized the `context`, as I'm not 100% sure that would work. Job arguments will need to be serialized by the executor.

Any ideas on how we can handle this scenario better, where I could access something like `context.entities.Metric` in the first example?

**Comment by Martinsos** [comment]
I had this idea of Job being defined via Action, instead of via ExtImport. So then Entities would again be injected via `context`.

But, you mentioned that Jobs serialize everything, all the args to them, so if they also need to serialize `context`, we might be in a problem.

Hmmmmm. So that means that job can import complex stuff, but it can't receive it as an argument? What if we didn't pass context as job argument -> instead we provided it (Wasp provided it) to Job as logic? So I am guessing that right now, when we define `job.perform`, that is given more or less directly to the pg-boss. Can't we just wrap it into additional function, that injects `context` into it? And then we give all that to pg-boss? Am I talking nonsense hm, maybe I missed the whole point? I guess what I am trying to say is that we could inject `context` in the runtime of the job, not as an argument (whatever `runtime` means here I am missing words to express myself).

**Comment by Martinsos** [comment]
Good questions about `setupFn` and possible middleware!

What is good with `context` is that it is easy for us to modify the Entities as needed + code is easier to test (entities are injected, not imported).
But, it is not always easy to have context.

On the other hand, if we provide direct ways to import Entities, then they can always do that and we can't force them to use Entities from the `context`.

I am also not sure what is better, to be honest. We could say that `setupFn` takes optional parameter `context` that contains all the entities :D.
Or we could say they must not import entities in Operations (but it will be hard to stop them?). That might be enough, it is not type-level safe, but in practice it will function ok.

Certainly worth more thought / observation!

**Comment by shayneczyzewski** [comment]
Yep, good points. I am torn as well :) Will give it more thought too! Thanks
