### ISSUE TITLE
Update React to version 18, plus a few other React libs

### ISSUE THREAD

**Issue by shayneczyzewski** [wasp-lang/wasp#723]
Once React 18 support hits a few more popular libraries and is used by most of the ecosystem, we should look into updating to it.

Since this update will likely be a breaking change, we should also consider updating:
- ~react-scripts to version 5~ we are using Vite now
- React Router to version 6

**Comment by infomiho** [comment]
This will break our `real-world` app example since it uses an older Material UI lib that depends on older React versions. But that's fine, we should update the `real-world` anyways.

**Comment by Martinsos** [comment]
Comment from other issue:

> React & ReactDOM & any other deps (testing lib etc) need to be updated to the latest.
Here is a Discord convo. This is a known request by now, but I think creating an issue for visibility wouldn't hurt :) I'd really like to push for this. Especially it's problematic if there is no way to influence npm install, like not possible to pass any flags etc. Therefore, my app is stuck because it needs a library that cannot be installed.
To be fair, this does raise a concern of a lock out situation, where devs need to have some sorts of work around / influence on the code and instead - relying on wasp dev to make an update. I think exposing npm install flags might also help in this specific case.

**Comment by Martinsos** [comment]
I released a canary version of Wasp v0.10.6 (latest version at the time of writing this) that uses React 18: https://github.com/wasp-lang/wasp/releases/tag/v0.10.6-react18-canary , since some users needed it urgently.

When we will be doing the upgrade from React 17 to 18, we should just takes this code and that should be it. But test it more. It is on the branch `react18-wasp0.10.6`.
