### ISSUE TITLE
Improve handling of invalid Prisma schemas

### ISSUE THREAD

**Issue by vincanger** [wasp-lang/wasp#805]
**Describe the bug**
I've already spoken with @shayneczyzewski about something I've been noticing with Prisma Entities. 

It seems some fields aren't being recognized/compiled by Wasp depending on where they are within the entity object:

![image](https://user-images.githubusercontent.com/70215737/200512108-f6a9337d-0666-4646-b9d9-acefc5bd7963.png)

For example, I didn't notice these two properties in Prisma Studio until I bumped them up to the top of the Entity object (see screenshot). I'm also quite sure I created these properties when I initially created the Entity. After bumping them up to the top of the entity object, I finally get the migrate DB message: `👀 ---- Your Prisma schema has changed, please run `wasp db migrate-dev` when ready.`

If I migrate the DB and then move the fields back down again, I get a `drop tables` warning. Maybe fields after a field with the "?" are affected? 🤷‍♂️

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/70215737/200514289-3e3df8a1-c8a0-42ec-8f91-8edd660906f6.png">

**Comment by vincanger** [comment]
```
app HiveMind {
  title: "HiveMind",
  db: {
    system: PostgreSQL
  },
  dependencies: [
    ("nodemailer", "^6.8.0")
  ]
}

job emailSender {
  executor: PgBoss, 
  perform: {
    fn: import { workerFunction } from "@ext/workers/emailSender.js"
  },
  schedule: {
    cron: "* * * * *" // every minute
  },
  entities: [Task]
}

entity Task {=psl
    id          Int       @id @default(autoincrement())
    createdAt   DateTime  @default(now())
    updatedAt   DateTime? @updatedAt  
    name        String    @unique
    status      String    @default("pending")
    message     String
    email       String
    deadline    String
    recurring   Int[]?
psl=}

route RootRoute { path: "/", to: MainPage }
page MainPage {
  component: import Main from "@ext/MainPage.js"
}
```

**Comment by shayneczyzewski** [comment]
Ok, so it turns out this is not actually a Wasp or Prisma bug per se. Wasp does support optional modifiers (they are used in some sample apps, and even in this example for `updatedAt`). However, neither Wasp nor Prisma supports both `[]` and `?` simultaneously: https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#type-modifiers

| Note: You cannot combine type modifiers - optional lists are not supported.

So I guess the correct behavior would be for us to show an error to the user, ideally, instead of just skipping whatever follows it. I will leave this open so we can improve this behavior in the future. 👍🏻

**Comment by shayneczyzewski** [comment]
@vincanger noted VS Code will give a warning if it was just a Prisma schema file.
![unknown](https://user-images.githubusercontent.com/523636/200578125-c8780018-b842-4ea1-bf7c-ef5ee24c0ac4.png)

This is a good use case for extending our `psql` support in some way.

**Comment by infomiho** [comment]
Done in #2035
