### ISSUE TITLE
Wasp: allow custom npm registries

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#869]
User asked for this feature: https://github.com/wasp-lang/wasp/issues/853 .

**Comment by GondoAI** [comment]
_'In order to keep things simpler for this first version, we enforced some limitations: no additional npm deps, no additional files, no TS, no advanced Wasp features.'_

Wondering the current status on;

- no additional files
- no additional NPM deps
- advanced WASP features

Looked through the repo and most linked discussions point back to the Dec 2022 code reorg. So just wondering if there was any work on these issues? Cheers, this is a great project!

**Comment by Martinsos** [comment]
Hey @GondoAI ! So those restrictions are regarding Mage (aka Wasp AI). Those restrictions might be lifted once we do further work on Mage and make it smarter / better, but we don't have a roadmap for that yet, since we are focusing more on Wasp, the web framework, at the moment.

As for Wasp the framework itself, we are working on restructuring that will make configuring it as a npm project easier, and that is heavily under way, I believe in the next month or so we will have something to show!

**Comment by sodic** [comment]
Wasp 0.12.0 supports package.json files, so this should work out of the box.
